#include <int.h>
#include <arch64.h>

#define IDT_ENTRY_DPT_RING0 (0 << 5)
#define IDT_ENTRY_DPT_RING1 (1 << 5)
#define IDT_ENTRY_DPT_RING2 (2 << 5)
#define IDT_ENTRY_DPT_RING3 (3 << 5)

#define IDT_ENTRY_PRESENT (1 << 7)

#define IDT_ENTRY_TYPE_LDT 2
#define IDT_ENTRY_TYPE_TSS_AVAIL 9
#define IDT_ENTRY_TYPE_TSS_BUSY 11
#define IDT_ENTRY_TYPE_CALL 12
#define IDT_ENTRY_TYPE_INTERUPT 14
#define IDT_ENTRY_TYPE_TRAP 15

extern "C" {
void do_int0x00();
void do_int0x01();
void do_int0x02();
void do_int0x03();
void do_int0x04();
void do_int0x05();
void do_int0x06();
void do_int0x07();
void do_int0x08();
void do_int0x09();
void do_int0x0A();
void do_int0x0B();
void do_int0x0C();
void do_int0x0D();
void do_int0x0E();
void do_int0x0F();

void do_int0x10();
void do_int0x11();
void do_int0x12();
void do_int0x13();
void do_int0x14();
void do_int0x15();
void do_int0x16();
void do_int0x17();
void do_int0x18();
void do_int0x19();
void do_int0x1A();
void do_int0x1B();
void do_int0x1C();
void do_int0x1D();
void do_int0x1E();
void do_int0x1F();

void do_int0x20();
void do_int0x21();
void do_int0x22();
void do_int0x23();
void do_int0x24();
void do_int0x25();
void do_int0x26();
void do_int0x27();
void do_int0x28();
void do_int0x29();
void do_int0x2A();
void do_int0x2B();
void do_int0x2C();
void do_int0x2D();
void do_int0x2E();
void do_int0x2F();

void do_int0x30();
void do_int0x31();
void do_int0x32();
void do_int0x33();
void do_int0x34();
void do_int0x35();
void do_int0x36();
void do_int0x37();
void do_int0x38();
void do_int0x39();
void do_int0x3A();
void do_int0x3B();
void do_int0x3C();
void do_int0x3D();
void do_int0x3E();
void do_int0x3F();

void do_int0x40();
void do_int0x41();
void do_int0x42();
void do_int0x43();
void do_int0x44();
void do_int0x45();
void do_int0x46();
void do_int0x47();
void do_int0x48();
void do_int0x49();
void do_int0x4A();
void do_int0x4B();
void do_int0x4C();
void do_int0x4D();
void do_int0x4E();
void do_int0x4F();

void do_int0x50();
void do_int0x51();
void do_int0x52();
void do_int0x53();
void do_int0x54();
void do_int0x55();
void do_int0x56();
void do_int0x57();
void do_int0x58();
void do_int0x59();
void do_int0x5A();
void do_int0x5B();
void do_int0x5C();
void do_int0x5D();
void do_int0x5E();
void do_int0x5F();

void do_int0x60();
void do_int0x61();
void do_int0x62();
void do_int0x63();
void do_int0x64();
void do_int0x65();
void do_int0x66();
void do_int0x67();
void do_int0x68();
void do_int0x69();
void do_int0x6A();
void do_int0x6B();
void do_int0x6C();
void do_int0x6D();
void do_int0x6E();
void do_int0x6F();

void do_int0x70();
void do_int0x71();
void do_int0x72();
void do_int0x73();
void do_int0x74();
void do_int0x75();
void do_int0x76();
void do_int0x77();
void do_int0x78();
void do_int0x79();
void do_int0x7A();
void do_int0x7B();
void do_int0x7C();
void do_int0x7D();
void do_int0x7E();
void do_int0x7F();

void do_int0x80();
void do_int0x81();
void do_int0x82();
void do_int0x83();
void do_int0x84();
void do_int0x85();
void do_int0x86();
void do_int0x87();
void do_int0x88();
void do_int0x89();
void do_int0x8A();
void do_int0x8B();
void do_int0x8C();
void do_int0x8D();
void do_int0x8E();
void do_int0x8F();

void do_int0x90();
void do_int0x91();
void do_int0x92();
void do_int0x93();
void do_int0x94();
void do_int0x95();
void do_int0x96();
void do_int0x97();
void do_int0x98();
void do_int0x99();
void do_int0x9A();
void do_int0x9B();
void do_int0x9C();
void do_int0x9D();
void do_int0x9E();
void do_int0x9F();

void do_int0xA0();
void do_int0xA1();
void do_int0xA2();
void do_int0xA3();
void do_int0xA4();
void do_int0xA5();
void do_int0xA6();
void do_int0xA7();
void do_int0xA8();
void do_int0xA9();
void do_int0xAA();
void do_int0xAB();
void do_int0xAC();
void do_int0xAD();
void do_int0xAE();
void do_int0xAF();

void do_int0xB0();
void do_int0xB1();
void do_int0xB2();
void do_int0xB3();
void do_int0xB4();
void do_int0xB5();
void do_int0xB6();
void do_int0xB7();
void do_int0xB8();
void do_int0xB9();
void do_int0xBA();
void do_int0xBB();
void do_int0xBC();
void do_int0xBD();
void do_int0xBE();
void do_int0xBF();

void do_int0xC0();
void do_int0xC1();
void do_int0xC2();
void do_int0xC3();
void do_int0xC4();
void do_int0xC5();
void do_int0xC6();
void do_int0xC7();
void do_int0xC8();
void do_int0xC9();
void do_int0xCA();
void do_int0xCB();
void do_int0xCC();
void do_int0xCD();
void do_int0xCE();
void do_int0xCF();

void do_int0xD0();
void do_int0xD1();
void do_int0xD2();
void do_int0xD3();
void do_int0xD4();
void do_int0xD5();
void do_int0xD6();
void do_int0xD7();
void do_int0xD8();
void do_int0xD9();
void do_int0xDA();
void do_int0xDB();
void do_int0xDD();
void do_int0xDC();
void do_int0xDE();
void do_int0xDF();

void do_int0xE0();
void do_int0xE1();
void do_int0xE2();
void do_int0xE3();
void do_int0xE4();
void do_int0xE5();
void do_int0xE6();
void do_int0xE7();
void do_int0xE8();
void do_int0xE9();
void do_int0xEA();
void do_int0xEB();
void do_int0xEC();
void do_int0xED();
void do_int0xEE();
void do_int0xEF();

void do_int0xF0();
void do_int0xF1();
void do_int0xF2();
void do_int0xF3();
void do_int0xF4();
void do_int0xF5();
void do_int0xF6();
void do_int0xF7();
void do_int0xF8();
void do_int0xF9();
void do_int0xFA();
void do_int0xFB();
void do_int0xFC();
void do_int0xFD();
void do_int0xFE();
void do_int0xFF();
}

namespace kmd {
namespace arch64 {
namespace idt {

struct {
	u16 offsetLow;
	u16 selector;
	u8 zero1;
	u8 flags;
	u16 offsetMiddle;
	u32 offsetHigh;
	u32 zero2;
}__attribute__((packed)) idt[256];

void setEntry(u8 index, u64 offset, u8 flags) {
	idt[index].flags = flags;
	idt[index].offsetLow = offset & 0xFFFF;
	idt[index].offsetMiddle = (offset >> 16) & 0xFFFF;
	idt[index].offsetHigh = (offset >> 32) & 0xFFFFFFFF;
	idt[index].selector = 0x08;
}

void lidt(u64 base, u16 limit) {
	struct {
		u16 limit;
		u64 base;
	}__attribute__((packed)) idtr = { limit, base };

	asm volatile("lidt %0" :: "m"(idtr));
}

void init() {
	setEntry(0x00, (u64) do_int0x00, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x01, (u64) do_int0x01, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x02, (u64) do_int0x02, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x03, (u64) do_int0x03, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x04, (u64) do_int0x04, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x05, (u64) do_int0x05, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x06, (u64) do_int0x06, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x07, (u64) do_int0x07, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x08, (u64) do_int0x08, IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x09, (u64) do_int0x09, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x0A, (u64) do_int0x0A, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x0B, (u64) do_int0x0B, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x0C, (u64) do_int0x0C, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x0D, (u64) do_int0x0D, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x0E, (u64) do_int0x0E, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x0F, (u64) do_int0x0F, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	setEntry(0x10, (u64) do_int0x10, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x11, (u64) do_int0x11, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x12, (u64) do_int0x12, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x13, (u64) do_int0x13, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x14, (u64) do_int0x14, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x15, (u64) do_int0x15, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x16, (u64) do_int0x16, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x17, (u64) do_int0x17, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x18, (u64) do_int0x18, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x19, (u64) do_int0x19, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x1A, (u64) do_int0x1A, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x1B, (u64) do_int0x1B, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x1C, (u64) do_int0x1C, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x1D, (u64) do_int0x1D, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x1E, (u64) do_int0x1E, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x1F, (u64) do_int0x1F, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	setEntry(0x20, (u64) do_int0x20, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x21, (u64) do_int0x21, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x22, (u64) do_int0x22, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x23, (u64) do_int0x23, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x24, (u64) do_int0x24, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x25, (u64) do_int0x25, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x26, (u64) do_int0x26, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x27, (u64) do_int0x27, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x28, (u64) do_int0x28, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x29, (u64) do_int0x29, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x2A, (u64) do_int0x2A, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x2B, (u64) do_int0x2B, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x2C, (u64) do_int0x2C, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x2D, (u64) do_int0x2D, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x2E, (u64) do_int0x2E, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x2F, (u64) do_int0x2F, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	setEntry(0x30, (u64) do_int0x30, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x31, (u64) do_int0x31, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x32, (u64) do_int0x32, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x33, (u64) do_int0x33, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x34, (u64) do_int0x34, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x35, (u64) do_int0x35, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x36, (u64) do_int0x36, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x37, (u64) do_int0x37, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x38, (u64) do_int0x38, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x39, (u64) do_int0x39, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x3A, (u64) do_int0x3A, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x3B, (u64) do_int0x3B, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x3C, (u64) do_int0x3C, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x3D, (u64) do_int0x3D, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x3E, (u64) do_int0x3E, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x3F, (u64) do_int0x3F, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	setEntry(0x40, (u64) do_int0x40, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x41, (u64) do_int0x41, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x42, (u64) do_int0x42, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x43, (u64) do_int0x43, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x44, (u64) do_int0x44, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x45, (u64) do_int0x45, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x46, (u64) do_int0x46, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x47, (u64) do_int0x47, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x48, (u64) do_int0x48, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x49, (u64) do_int0x49, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x4A, (u64) do_int0x4A, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x4B, (u64) do_int0x4B, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x4C, (u64) do_int0x4C, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x4D, (u64) do_int0x4D, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x4E, (u64) do_int0x4E, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x4F, (u64) do_int0x4F, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	setEntry(0x50, (u64) do_int0x50, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x51, (u64) do_int0x51, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x52, (u64) do_int0x52, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x53, (u64) do_int0x53, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x54, (u64) do_int0x54, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x55, (u64) do_int0x55, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x56, (u64) do_int0x56, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x57, (u64) do_int0x57, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x58, (u64) do_int0x58, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x59, (u64) do_int0x59, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x5A, (u64) do_int0x5A, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x5B, (u64) do_int0x5B, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x5C, (u64) do_int0x5C, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x5D, (u64) do_int0x5D, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x5E, (u64) do_int0x5E, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x5F, (u64) do_int0x5F, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	setEntry(0x60, (u64) do_int0x60, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x61, (u64) do_int0x61, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x62, (u64) do_int0x62, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x63, (u64) do_int0x63, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x64, (u64) do_int0x64, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x65, (u64) do_int0x65, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x66, (u64) do_int0x66, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x67, (u64) do_int0x67, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x68, (u64) do_int0x68, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x69, (u64) do_int0x69, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x6A, (u64) do_int0x6A, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x6B, (u64) do_int0x6B, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x6C, (u64) do_int0x6C, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x6D, (u64) do_int0x6D, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x6E, (u64) do_int0x6E, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x6F, (u64) do_int0x6F, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	setEntry(0x70, (u64) do_int0x70, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x71, (u64) do_int0x71, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x72, (u64) do_int0x72, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x73, (u64) do_int0x73, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x74, (u64) do_int0x74, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x75, (u64) do_int0x75, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x76, (u64) do_int0x76, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x77, (u64) do_int0x77, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x78, (u64) do_int0x78, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x79, (u64) do_int0x79, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x7A, (u64) do_int0x7A, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x7B, (u64) do_int0x7B, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x7C, (u64) do_int0x7C, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x7D, (u64) do_int0x7D, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x7E, (u64) do_int0x7E, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x7F, (u64) do_int0x7F, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	setEntry(0x80, (u64) do_int0x80, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x81, (u64) do_int0x81, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x82, (u64) do_int0x82, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x83, (u64) do_int0x83, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x84, (u64) do_int0x84, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x85, (u64) do_int0x85, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x86, (u64) do_int0x86, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x87, (u64) do_int0x87, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x88, (u64) do_int0x88, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x89, (u64) do_int0x89, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x8A, (u64) do_int0x8A, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x8B, (u64) do_int0x8B, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x8C, (u64) do_int0x8C, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x8D, (u64) do_int0x8D, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x8E, (u64) do_int0x8E, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x8F, (u64) do_int0x8F, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	setEntry(0x90, (u64) do_int0x90, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x91, (u64) do_int0x91, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x92, (u64) do_int0x92, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x93, (u64) do_int0x93, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x94, (u64) do_int0x94, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x95, (u64) do_int0x95, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x96, (u64) do_int0x96, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x97, (u64) do_int0x97, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x98, (u64) do_int0x98, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x99, (u64) do_int0x99, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x9A, (u64) do_int0x9A, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x9B, (u64) do_int0x9B, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x9C, (u64) do_int0x9C, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x9D, (u64) do_int0x9D, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x9E, (u64) do_int0x9E, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0x9F, (u64) do_int0x9F, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	setEntry(0xA0, (u64) do_int0xA0, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xA1, (u64) do_int0xA1, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xA2, (u64) do_int0xA2, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xA3, (u64) do_int0xA3, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xA4, (u64) do_int0xA4, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xA5, (u64) do_int0xA5, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xA6, (u64) do_int0xA6, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xA7, (u64) do_int0xA7, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xA8, (u64) do_int0xA8, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xA9, (u64) do_int0xA9, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xAA, (u64) do_int0xAA, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xAB, (u64) do_int0xAB, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xAC, (u64) do_int0xAC, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xAD, (u64) do_int0xAD, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xAE, (u64) do_int0xAE, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xAF, (u64) do_int0xAF, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	setEntry(0xB0, (u64) do_int0xB0, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xB1, (u64) do_int0xB1, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xB2, (u64) do_int0xB2, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xB3, (u64) do_int0xB3, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xB4, (u64) do_int0xB4, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xB5, (u64) do_int0xB5, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xB6, (u64) do_int0xB6, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xB7, (u64) do_int0xB7, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xB8, (u64) do_int0xB8, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xB9, (u64) do_int0xB9, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xBA, (u64) do_int0xBA, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xBB, (u64) do_int0xBB, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xBC, (u64) do_int0xBC, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xBD, (u64) do_int0xBD, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xBE, (u64) do_int0xBE, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xBF, (u64) do_int0xBF, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	setEntry(0xC0, (u64) do_int0xC0, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xC1, (u64) do_int0xC1, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xC2, (u64) do_int0xC2, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xC3, (u64) do_int0xC3, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xC4, (u64) do_int0xC4, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xC5, (u64) do_int0xC5, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xC6, (u64) do_int0xC6, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xC7, (u64) do_int0xC7, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xC8, (u64) do_int0xC8, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xC9, (u64) do_int0xC9, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xCA, (u64) do_int0xCA, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xCB, (u64) do_int0xCB, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xCC, (u64) do_int0xCC, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xCD, (u64) do_int0xCD, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xCE, (u64) do_int0xCE, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xCF, (u64) do_int0xCF, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	setEntry(0xD0, (u64) do_int0xD0, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xD1, (u64) do_int0xD1, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xD2, (u64) do_int0xD2, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xD3, (u64) do_int0xD3, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xD4, (u64) do_int0xD4, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xD5, (u64) do_int0xD5, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xD6, (u64) do_int0xD6, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xD7, (u64) do_int0xD7, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xD8, (u64) do_int0xD8, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xD9, (u64) do_int0xD9, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xDA, (u64) do_int0xDA, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xDB, (u64) do_int0xDB, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xDC, (u64) do_int0xDC, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xDD, (u64) do_int0xDD, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xDE, (u64) do_int0xDE, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xDF, (u64) do_int0xDF, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	setEntry(0xE0, (u64) do_int0xE0, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xE1, (u64) do_int0xE1, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xE2, (u64) do_int0xE2, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xE3, (u64) do_int0xE3, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xE4, (u64) do_int0xE4, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xE5, (u64) do_int0xE5, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xE6, (u64) do_int0xE6, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xE7, (u64) do_int0xE7, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xE8, (u64) do_int0xE8, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xE9, (u64) do_int0xE9, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xEA, (u64) do_int0xEA, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xEB, (u64) do_int0xEB, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xEC, (u64) do_int0xEC, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xED, (u64) do_int0xED, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xEE, (u64) do_int0xEE, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xEF, (u64) do_int0xEF, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	setEntry(0xF0, (u64) do_int0xF0, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xF1, (u64) do_int0xF1, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xF2, (u64) do_int0xF2, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xF3, (u64) do_int0xF3, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xF4, (u64) do_int0xF4, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xF5, (u64) do_int0xF5, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xF6, (u64) do_int0xF6, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xF7, (u64) do_int0xF7, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xF8, (u64) do_int0xF8, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xF9, (u64) do_int0xF9, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xFA, (u64) do_int0xFA, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xFB, (u64) do_int0xFB, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xFC, (u64) do_int0xFC, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xFD, (u64) do_int0xFD, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xFE, (u64) do_int0xFE, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);
	setEntry(0xFF, (u64) do_int0xFF, IDT_ENTRY_PRESENT | IDT_ENTRY_DPT_RING0 | IDT_ENTRY_TYPE_INTERUPT);

	lidt((u64) idt, sizeof(idt) - 1);
}

}
}
}
